[alias]
test-it = "test --features integration,testing -- --test-threads=1"
test-e2e = "test --features e2e,testing -- --test-threads=1"
test-all = "test --features integration,e2e,testing -- --test-threads=1"
